"""ActionLog values are now nullable

Revision ID: 8b232e6f9c8d
Revises: 0c86dfb253be
Create Date: 2024-11-18 15:14:27.426587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b232e6f9c8d'
down_revision: Union[str, None] = '0c86dfb253be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs') as batch_op:
        batch_op.alter_column('cash',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('xp',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('hp',
                   existing_type=sa.INTEGER(),
                   nullable=True)
        batch_op.alter_column('sp',
                   existing_type=sa.INTEGER(),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action_logs') as batch_op:
        batch_op.alter_column('sp',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('hp',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('xp',
                   existing_type=sa.INTEGER(),
                   nullable=False)
        batch_op.alter_column('cash',
                   existing_type=sa.INTEGER(),
                   nullable=False)
    # ### end Alembic commands ###
