"""Task fields are now nullable

Revision ID: ba8159d785ca
Revises: 8b232e6f9c8d
Create Date: 2024-11-18 16:25:39.899543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba8159d785ca'
down_revision: Union[str, None] = '8b232e6f9c8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due', sa.DateTime(), nullable=True))
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cash',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(),
               nullable=True)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('objectiveID')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objectiveID', sa.INTEGER(), nullable=False))
        # batch_op.create_foreign_key("fk_tasks_objectives_objectiveID", 'objectives', ['objectiveID'], ['ID'], ondelete='CASCADE')
        batch_op.alter_column('duration',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('difficulty',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('cash',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('xp',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('due')

    # ### end Alembic commands ###
