"""Initial migration

Revision ID: 0c86dfb253be
Revises: 
Create Date: 2024-11-18 10:26:10.161074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c86dfb253be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_logs", schema=None) as batch_op:
        batch_op.create_foreign_key("fk_users_userID", 'users', ['userID'], ['ID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("action_logs", schema=None) as batch_op:
        batch_op.drop_constraint("fk_users_userID", type_='foreignkey')
    # ### end Alembic commands ###
