"""ActionLog date re-addition attempt

Revision ID: 19756763f9a2
Revises: ba8159d785ca
Create Date: 2024-11-18 16:46:56.945692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19756763f9a2'
down_revision: Union[str, None] = 'ba8159d785ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("action_logs", sa.Column('date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("action_logs", 'date')
    # ### end Alembic commands ###
